In [1]:
import numpy as np
import pandas as pd


import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

import warnings
warnings.filterwarnings('ignore')

In [2]:
con = sqlite3.connect("movie.sqlite")
cur = con.cursor()

1.- ¿Cuáles son los datos de las películas?

In [3]:
cur.execute('SELECT * FROM movies')

movies = cur.fetchall()

#Note - fetchall() --> recupera todas las filas para la consulta actual; si no hay filas disponibles, devuelve una lista vacía.
movies = pd.DataFrame(movies, columns = ['id', 'original_title', 'budget', 'popularity', 'release_date', 'revenue', 'title', 'vote_average', 'vote_count', 'overview', 'tagline', 'uid', 'director_id'])

print('Tamaño de los datos :',movies.shape)
print('\n\n\n')
movies.head(3)

Tamaño de los datos : (4773, 13)

,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id
0,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762
1,43598,Pirates of the Caribbean: At World's End,300000000,139,2007-05-19,961000000,Pirates of the Caribbean: At World's End,6.9,4500,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",285,4763
2,43599,Spectre,245000000,107,2015-10-26,880674609,Spectre,6.3,4466,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,206647,4764

2.- Obtén los datos de los directores.

In [4]:
cur.execute('SELECT * FROM directors')

directors = cur.fetchall()


directors = pd.DataFrame(directors, columns = ['name', 'id', 'gender', 'uid', 'department'])




directors.head(3)

             name    id  gender   uid department
0   James Cameron  4762       2  2710  Directing
1  Gore Verbinski  4763       2  1704  Directing
2      Sam Mendes  4764       2    39  Directing

3.- ¿Cuántas películas hay en la base de datos?

In [5]:
cur.execute('SELECT COUNT (*) from movies;')


count = cur.fetchall()
print("El número de películas es \t\t\t :",count[0])

El número de películas es 			 : (4773,)

4.- Encuentra a los siguientes directores: James Cameron ; Luc Besson ; John Woo.

In [6]:
cur.execute("SELECT * from directors where name == 'James Cameron' or name =='Luc Besson' or name =='John Woo'")

# where - WHERE cláusula para obtener las filas que cumplieron estas condiciones.

tres_directors = cur.fetchall()

print("Los directores: \t :",tres_directors)

Los directores: 	 : [('James Cameron', 4762, 2, 2710, 'Directing'), ('John Woo', 4893, 2, 11401, 'Directing'), ('Luc Besson', 4949, 2, 59, 'Directing')]

5.- Busca todos los directores con nombres que comienzan con Steven

In [7]:
cur.execute("SELECT * from directors where name LIKE 'Steven%'")

#LIKE  - LIKE El operador distingue entre mayúsculas y minúsculas, funciona como si los nombres comenzaran con una palabra en particular deberían coincidir.

# El patrón d% que utiliza el comodín del signo de porcentaje ( %) coincide con cualquier cadena que comience con s e.g.,danger and dance,door.


name_like = cur.fetchall()
print("TLos nombres son: \n \t", name_like)

TLos nombres son:
 	 [('Steven Spielberg', 4799, 2, 488, 'Directing'), ('Steven Soderbergh', 4909, 2, 1884, 'Directing'), ('Steven Brill', 5013, 2, 32593, 'Directing'), ('Steven Zaillian', 5117, 2, 2260, 'Directing'), ('Steven Quale', 5216, 2, 93214, 'Directing'), ('Steven Seagal', 5221, 2, 23880, 'Directing'), ('Steven E. de Souza', 5390, 2, 1726, 'Directing'), ('Steven Shainberg', 5803, 2, 67795, 'Directing'), ('Steven R. Monroe', 6713, 2, 88039, 'Directing')]

6.- Cuente el número de directoras.

In [8]:
cur.execute(" SELECT COUNT(*) from directors where gender == 1")


female_directors = cur.fetchall()
print("El número de directoras son: \n \t", female_directors[0])

El número de directoras son:
 	 (150,)

7.- ¿Encuentra el nombre de la décima primera mujer directora?

In [9]:
cur.execute("SELECT name FROM directors WHERE gender == 1 ORDER by id asc limit 1 OFFSET 10")

#ORDER by - Para ordenar los datos usamos orden por, ascendente (asc) O descendente (dsc)
#LIMIT -  LIMIT cláusula para limitar el número de filas devueltas por la consulta.

# LIMIT_OFFSET - cláusula para obtener la enésima fila más alta o la enésima más baja
tenth= cur.fetchall()
print("TEl nombre es: \n\n \t", tenth[0])

TEl nombre es:

 	 ('Karyn Kusama',)

8.- ¿Cuáles son las tres películas más populares?

In [10]:
cur.execute("SELECT original_title  FROM movies ORDER by popularity desc limit 3")
most_popular = cur.fetchall()
print("Las tres películas más populares son: \n\n \t", most_popular)

Las tres películas más populares son:

 	 [('Minions',), ('Interstellar',), ('Deadpool',)]

9.- ¿Cuáles son las 3 películas más rentables?

In [11]:
cur.execute("SELECT original_title  FROM movies ORDER by budget desc limit 3")

most_bankable = cur.fetchall()
print("Las tres peliculas más rentables son: \n\n \t", most_bankable)

Las tres peliculas más rentables son:

 	 [('Pirates of the Caribbean: On Stranger Tides',), ("Pirates of the Caribbean: At World's End",), ('Avengers: Age of Ultron',)]

10.- Explica de manera detallada cómo funcionan los JOINS en SQL. Puedes tomar de referencia lo siguiente:


*   https://www.techonthenet.com/sqlite/joins.php
*   https://www.tutorialspoint.com/sqlite/sqlite_using_joins.htm

10.- ¿Qué películas fueron dirigidas por Brenda Chapman?

In [12]:
cur.execute("SELECT original_title FROM movies  JOIN directors ON directors.id = movies.director_id WHERE directors.name = 'Brenda Chapman';")


directed_by= cur.fetchall()
print("Brenda Chapman \n\n \t", directed_by)

Brenda Chapman

 	 [('Brave',)]

11.- ¿Qué director ha realizado más películas?

In [13]:
cur.execute("SELECT name FROM directors  JOIN movies ON directors.id = movies.director_id GROUP BY director_id ORDER BY count(name) DESC limit 1;")

directed_by= cur.fetchall()
print("El director con más películas \n\n \t", directed_by)

El director con más películas

 	 [('Steven Spielberg',)]

12.- Enumere las 10 películas más populares

In [14]:
cur.execute('SELECT original_title, name, release_date, popularity, revenue FROM movies JOIN directors ON movies.director_id = directors.id ORDER BY popularity DESC')
mostPopular = cur.fetchall()
mostPopular = pd.DataFrame(mostPopular, columns = ['original_title', 'director_name', 'release_date', 'popularity', 'revenue'])
mostPopular.head(10)

,original_title,director_name,release_date,popularity,revenue
0,Minions,Kyle Balda,2015-06-17,875,1156730962
1,Interstellar,Christopher Nolan,2014-11-05,724,675120017
2,Deadpool,Tim Miller,2016-02-09,514,783112979
3,Guardians of the Galaxy,James Gunn,2014-07-30,481,773328629
4,Mad Max: Fury Road,George Miller,2015-05-13,434,378858340
5,Jurassic World,Colin Trevorrow,2015-06-09,418,1513528810
6,Pirates of the Caribbean: The Curse of the Bla...,Gore Verbinski,2003-07-09,271,655011224
7,Dawn of the Planet of the Apes,Matt Reeves,2014-06-26,243,710644566
8,The Hunger Games: Mockingjay - Part 1,Francis Lawrence,2014-11-18,206,752100229
9,Big Hero 6,Chris Williams,2014-10-24,203,652105443

13.- ¿Cuáles son las 10 películas con mayores ingresos?

In [15]:
cur.execute('SELECT original_title, name, release_date, revenue FROM movies JOIN directors ON movies.director_id = directors.id ORDER BY revenue DESC')
mostProfit = cur.fetchall()
mostProfit = pd.DataFrame(mostProfit, columns = ['original_title', 'director_name', 'release_date', 'revenue'])
mostProfit.head(10)

               original_title    director_name release_date     revenue
0                      Avatar    James Cameron   2009-12-10  2787965087
1                     Titanic    James Cameron   1997-11-18  1845034188
2                The Avengers      Joss Whedon   2012-04-25  1519557910
3              Jurassic World  Colin Trevorrow   2015-06-09  1513528810
4                   Furious 7        James Wan   2015-04-01  1506249360
5     Avengers: Age of Ultron      Joss Whedon   2015-04-22  1405403694
6                      Frozen       Chris Buck   2013-11-27  1274219009
7                  Iron Man 3      Shane Black   2013-04-18  1215439994
8                     Minions       Kyle Balda   2015-06-17  1156730962
9  Captain America: Civil War    Anthony Russo   2016-04-27  1153304495

14.- ¿Películas de James Cameron?

In [16]:
cur.execute('SELECT original_title, release_date, budget, revenue, popularity, vote_average FROM directors JOIN movies ON directors.id = movies.director_id WHERE name = "James Cameron" ORDER BY revenue DESC')
moviesByJamesCameron = cur.fetchall()
moviesByJamesCameron = pd.DataFrame(moviesByJamesCameron, columns = ['original_title', 'release_date', 'budget', 'revenue', 'popularity', 'vote_average'])
moviesByJamesCameron

,original_title,release_date,budget,revenue,popularity,vote_average
0,Avatar,2009-12-10,237000000,2787965087,150,7.2
1,Titanic,1997-11-18,200000000,1845034188,100,7.5
2,Terminator 2: Judgment Day,1991-07-01,100000000,520000000,101,7.7
3,True Lies,1994-07-14,115000000,378882411,38,6.8
4,Aliens,1986-07-18,18500000,183316455,67,7.7
5,The Abyss,1989-08-09,70000000,90000098,24,7.1
6,The Terminator,1984-10-26,6400000,78371200,74,7.3

15.- Enumere los nombres de los directores con la cantidad de películas y los ingresos.

In [17]:
cur.execute('SELECT name, COUNT(original_title), SUM(revenue)FROM directors JOIN movies ON directors.id = movies.director_id GROUP BY name ORDER BY SUM(revenue) DESC')
mostProfitableDirector = cur.fetchall()
mostProfitableDirector = pd.DataFrame(mostProfitableDirector, columns = ['director_name', 'movies', 'revenue'])
mostProfitableDirector.head(10)

       director_name  movies     revenue
0   Steven Spielberg      27  9147393164
1      Peter Jackson       9  6498642820
2      James Cameron       7  5883569439
3        Michael Bay      12  5832524638
4  Christopher Nolan       8  4227483234
5     Chris Columbus      11  3725631503
6    Robert Zemeckis      13  3590622002
7       George Lucas       5  3339113893
8         Tim Burton      14  3337418241
9       Ridley Scott      16  3189557997

In [18]:
cur.execute('SELECT original_title, release_date, budget, revenue, popularity, vote_average FROM directors JOIN movies ON directors.id = movies.director_id WHERE name = "Steven Spielberg" ORDER BY release_date DESC')
moviesByStevenSpielberg = cur.fetchall()
moviesByStevenSpielberg = pd.DataFrame(moviesByStevenSpielberg, columns = ['original_title', 'release_date', 'budget', 'revenue', 'popularity', 'vote_average'])
moviesByStevenSpielberg

,original_title,release_date,budget,revenue,popularity,vote_average
0,The BFG,2016-06-01,140000000,183345589,44,6.0
1,Bridge of Spies,2015-10-15,40000000,165478348,48,7.2
2,Lincoln,2012-11-09,65000000,275293450,36,6.7
3,War Horse,2011-12-25,66000000,177584879,29,7.0
4,The Adventures of Tintin,2011-10-25,130000000,371940071,89,6.7
5,Indiana Jones and the Kingdom of the Crystal S...,2008-05-21,185000000,786636033,75,5.7
6,Munich,2005-12-22,70000000,130358911,29,6.9
7,War of the Worlds,2005-06-28,132000000,591739379,48,6.2
8,The Terminal,2004-06-17,60000000,219417255,57,7.0
9,Catch Me If You Can,2002-12-25,52000000,352114312,73,7.7
10,Minority Report,2002-06-20,102000000,358372926,65,7.1
11,A.I. Artificial Intelligence,2001-06-29,100000000,235926552,34,6.8
12,Saving Private Ryan,1998-07-24,70000000,481840909,76,7.9
13,Amistad,1997-12-03,36000000,74000000,3,6.8
14,The Lost World: Jurassic Park,1997-05-23,73000000,229074524,2,6.2
15,Schindler's List,1993-11-29,22000000,321365567,104,8.3
16,Jurassic Park,1993-06-11,63000000,920100000,40,7.6
17,Hook,1991-12-11,70000000,300854823,33,6.6
18,Indiana Jones and the Last Crusade,1989-05-24,48000000,474171806,80,7.6
19,The Color Purple,1985-12-18,15000000,146292009,17,7.7
20,Indiana Jones and the Temple of Doom,1984-05-23,28000000,333000000,66,7.1
21,Twilight Zone: The Movie,1983-06-24,10000000,29450919,12,6.2
22,E.T. the Extra-Terrestrial,1982-04-03,10500000,792910554,56,7.3
23,Raiders of the Lost Ark,1981-06-12,18000000,389925971,68,7.7
24,1941,1979-12-13,35000000,31755742,10,5.6
25,Close Encounters of the Third Kind,1977-11-16,20000000,303788635,52,7.2
26,Jaws,1975-06-18,7000000,470654000,50,7.5